version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: storage
      POSTGRES_PASSWORD: storage123
      POSTGRES_DB: storagedb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/storagedb
      SPRING_DATASOURCE_USERNAME: storage
      SPRING_DATASOURCE_PASSWORD: storage123
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
