version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chem
      POSTGRES_PASSWORD: chem123
      POSTGRES_DB: chemdb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on: [db]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/chemdb
      SPRING_DATASOURCE_USERNAME: chem
      SPRING_DATASOURCE_PASSWORD: chem123
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
